apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-capstone
  labels:
    app: aws-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aws-capstone
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: aws-capstone
    spec:
      containers:
        - image: miduskas/aws-capstone
          imagePullPolicy: Always
          name: aws-capstone
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: aws-capstone
  labels:
    app: aws-capstone
spec:
  type: LoadBalancer
  selector:
    app: aws-capstone
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
